Error when detecting wireless packets
Missing () when instantiating RadioPacket is causing following error.

"this.payload = new RadioPacket.decode(buf, 0);
                       ^
TypeError: undefined is not a function"

line should be

this.payload = new RadioPacket().decode(buf, 0);